export const PLAYERS_IN_ROOM = 2;
export const MAX_PLAYERS_IN_ROOM = 10;
export const MIN_PLAYERS_IN_ROOM = 2;
export const ROUND_TIME_IN_SECONDS = 30;
export const MAX_ROUND_TIME_IN_SECONDS = 120;
export const MIN_ROUND_TIME_IN_SECONDS = 30;
export const CHOOSING_WORD_TIME_IN_SECONDS = 10;
export const MAX_CHOOSING_WORD_TIME_IN_SECONDS = 30;
export const MIN_CHOOSING_WORD_TIME_IN_SECONDS = 5;

export const STARTING_TIME_IN_SECONDS = 2;

export const POINTS_PER_LEVEL = 100;

export const Difficalty = {
  EASY: "easy",
  MEDIUM: "medium",
  HARD: "hard",
} as const;

export const WORDS = {
  space: [
    "astronaut",
    "alien",
    "spaceship",
    "planet",
    "stars",
    "moon",
    "comet",
    "galaxy",
    "satellite",
    "telescope",
    "meteor",
    "black hole",
    "solar system",
    "nebula",
    "sun",
    "asteroid",
    "orbit",
    "gravity",
    "milky way",
    "space station",
  ],
  animals: [
    "dog",
    "cat",
    "bird",
    "fish",
    "snake",
    "turtle",
    "rabbit",
    "hamster",
    "elephant",
    "lion",
    "giraffe",
    "kangaroo",
    "hippopotamus",
    "cheetah",
    "whale",
    "octopus",
    "zebra",
    "penguin",
    "frog",
    "crocodile",
  ],
  food: [
    "apple",
    "banana",
    "orange",
    "pear",
    "strawberry",
    "watermelon",
    "pizza",
    "burger",
    "ice cream",
    "cake",
    "spaghetti",
    "chocolate",
    "bread",
    "cheese",
    "chicken",
    "steak",
    "pancakes",
    "fries",
    "donut",
    "sushi",
  ],
  sports: [
    "basketball",
    "football",
    "soccer",
    "baseball",
    "tennis",
    "golf",
    "volleyball",
    "swimming",
    "boxing",
    "badminton",
    "hockey",
    "rugby",
    "cricket",
    "skiing",
    "snowboarding",
    "table tennis",
    "archery",
    "cycling",
    "marathon",
    "gymnastics",
  ],
  transport: [
    "car",
    "bus",
    "train",
    "bicycle",
    "helicopter",
    "plane",
    "boat",
    "motorcycle",
    "truck",
    "scooter",
    "subway",
    "tram",
    "hoverboard",
    "hot air balloon",
    "ferry",
    "tank",
    "jetski",
    "roller skates",
    "skateboard",
    "parachute",
  ],
  nature: [
    "tree",
    "flower",
    "river",
    "mountain",
    "forest",
    "beach",
    "lake",
    "desert",
    "rainbow",
    "waterfall",
    "cave",
    "volcano",
    "island",
    "cloud",
    "sunrise",
    "sunset",
    "snowflake",
    "hurricane",
    "ocean",
    "moonlight",
  ],
  toys: [
    "teddy bear",
    "doll",
    "lego",
    "puzzle",
    "robot",
    "kite",
    "ball",
    "yo-yo",
    "board game",
    "remote car",
    "jigsaw",
    "action figure",
    "trampoline",
    "frisbee",
    "magic set",
    "slime",
    "marbles",
    "dollhouse",
    "stuffed animal",
    "toy train",
  ],
  jobs: [
    "teacher",
    "doctor",
    "firefighter",
    "police",
    "chef",
    "farmer",
    "dentist",
    "nurse",
    "pilot",
    "artist",
    "lawyer",
    "engineer",
    "singer",
    "actor",
    "mechanic",
    "scientist",
    "architect",
    "writer",
    "plumber",
    "soldier",
  ],
  buildings: [
    "house",
    "school",
    "hospital",
    "museum",
    "library",
    "zoo",
    "stadium",
    "skyscraper",
    "bridge",
    "castle",
    "church",
    "prison",
    "factory",
    "farm",
    "lighthouse",
    "windmill",
    "tower",
    "market",
    "hotel",
    "temple",
  ],
  clothes: [
    "shirt",
    "pants",
    "hat",
    "dress",
    "shoes",
    "gloves",
    "scarf",
    "jacket",
    "sunglasses",
    "socks",
    "sweater",
    "boots",
    "tie",
    "shorts",
    "skirt",
    "belt",
    "jeans",
    "t-shirt",
    "swimsuit",
    "nightgown",
  ],
};
